/* [Programmers] 164673. 조건에 부합하는 중고거래 댓글 조회하기 */

SELECT b.TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, date_format(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD as b, USED_GOODS_REPLY as r
WHERE b.BOARD_ID = r.BOARD_ID and YEAR(b.CREATED_DATE) = '2022' and MONTH(b.CREATED_DATE) = '10'
ORDER BY r.CREATED_DATE, b.TITLE;
