/* [Programmers] 157341. 대여 기록이 존재하는 자동차 리스트 구하기 */

SELECT DISTINCT INFO.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR as INFO
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as HISTORY
ON INFO.CAR_ID = HISTORY.CAR_ID
WHERE INFO.CAR_TYPE = "세단" and MONTH(START_DATE) = 10
ORDER BY INFO.CAR_ID desc;