/* [Programmers] 164668. 조건에 맞는 사용자와 총 거래금액 조회하기 */

SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as UGB
INNER JOIN USED_GOODS_USER as UGU
ON UGU.USER_ID = UGB.WRITER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;